name = "zola-dark-denim"
description = "A simple landing page theme"
license = "MIT"
homepage = "https://github.com/swilcox/zola-dark-denim"
# The minimum version of Zola required
min_version = "0.5.0"
# An optional live demo URL
demo = "https://zola-dark-denim.github.io"

[author]
name = "Steven Wilcox"
homepage = "https://wilcox.be"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola

[extra]
